(define (main)
  (print-number *compiler-end*)
  (let* ((p1 (malloc 100))
         (p2 (malloc 100))
         (p3 (malloc 100))
         (p4 (malloc 100)))
    (print-number p1)
    (print-number p2)
    (print-number p3)
    (print-number p4)
    (free p1)
    (free p2)
    (print-number (malloc 200)))
  (exit!))
