(define (main)
  (let ((a 10)
        (b 30)
        (c 40)
        (d 17))
    (putchar (+ a (+ b (+ c d))))
    (putchar #\newline))
  ;; (let walk ((a 10) (b 0))
  ;;   (print-number 42))
  )
    ;; (if (equ? a b)
    ;;     (noop)
    ;;     (begin
    ;;       ;; (print-number a)
    ;;       ;; (print-number b)
    ;;       (print-number walk)
    ;;       (walk (- a 1) (+ b 1))))))
