(define (test e f)
  (let ((a 10)
        (b 30)
        (c e)
        (d 15))
    (putchar (+ a (+ b (+ c d))))
    (putchar #\newline)
    (let ((a #\a)
          (b #\b)
          (c #\c))
      (putchar a)
      (putchar b)
      (putchar c)
      (print-number (- (+ e f) 10))))
  (print-number e)
  (print-number f))

(define (main)
  (test 42 10)
  (exit!))
