name: build and test nienor
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: any
      - name: Download dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y make clang
      - name: Install owl lisp
        shell: bash
        run: |
          git clone https://gitlab.com/owl-lisp/owl
          ( cd owl && make && sudo make install )
      - name: Install uxn
        shell: bash
        run: |
          wget https://git.sr.ht/~rabbits/uxn11/blob/f366f0db973b2a9ee2c9b19df02a5d6951072b32/src/uxncli.c
          clang -O2 -o uxncli uxncli.c
          sudo cp uxncli /bin/
      - name: Run tests
        shell: bash
        run: |
          UXNEMU=uxncli make test CC=clang
      - name: Compile windows binary
        shell: bash
        run: |
          sudo add-apt-repository universe
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine wine32 wget
          wget https://pub.krzysckh.org/owl-winbuilds/ol32-small.exe
          make bin/nienor.exe
          mkdir build
          cp bin/nienor.exe build/nienor.exe
          cp bin/nienor build/nienor-`clang -dumpmachine`
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nienor
          path: build/
